/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Erc20StandardBridge } from "./Erc20StandardBridge";
export * as factories from "./factories";
export { Erc20StandardBridge__factory } from "./factories/Erc20StandardBridge__factory";
