/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IGlpTimelock,
  IGlpTimelockInterface,
} from "../../../contracts/migration/IGlpTimelock";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_vault",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_taxBasisPoints",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_stableTaxBasisPoints",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_mintBurnFeeBasisPoints",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_swapFeeBasisPoints",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_stableSwapFeeBasisPoints",
        type: "uint256",
      },
    ],
    name: "setSwapFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IGlpTimelock__factory {
  static readonly abi = _abi;
  static createInterface(): IGlpTimelockInterface {
    return new utils.Interface(_abi) as IGlpTimelockInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IGlpTimelock {
    return new Contract(address, _abi, signerOrProvider) as IGlpTimelock;
  }
}
